ARG UBUNTU_VERSION=latest
FROM ubuntu:$UBUNTU_VERSION

SHELL [ "/bin/bash", "-c" ]

ARG UBUNTU_VERSION
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

RUN apt update -yq \ 
    && apt upgrade -yq \
    && apt install -yq \
        ca-certificates \
        sudo \
        curl \
        wget \
        git \
        unzip \
        tar \
        jq \
        python3 \
        python3-pip \
        default-jdk

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \ 
    && . $HOME/.nvm/nvm.sh && \
    nvm install --lts && \
    nvm use --lts && \
    node -v && npm -v

ENV PATH="${PATH}:~/.local/bin"
# RUN pip install semgrep \ 
#     && semgrep --version

# COPY --from=registry.gitlab.com/security-products/semgrep:3 /rules /semgrep-rules